// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgY13jjMSjViKT77wVTVHApZtakPQJkd8',
    appId: '1:960446114350:web:7fae782bf929fd06854dbf',
    messagingSenderId: '960446114350',
    projectId: 'malov-mis',
    authDomain: 'malov-mis.firebaseapp.com',
    storageBucket: 'malov-mis.appspot.com',
    measurementId: 'G-0LVTT4L6DB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCltxAO-2r5ztDQVCKZGs1Yv-j1FfeP6h4',
    appId: '1:960446114350:android:1eb1b3593f19034a854dbf',
    messagingSenderId: '960446114350',
    projectId: 'malov-mis',
    storageBucket: 'malov-mis.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6ho2oarreidNRTCFr9zHPwliMxOYMs74',
    appId: '1:960446114350:ios:35cd877ee8f37c61854dbf',
    messagingSenderId: '960446114350',
    projectId: 'malov-mis',
    storageBucket: 'malov-mis.appspot.com',
    iosClientId: '960446114350-c1sv1h1v376rg7g7lpft1rt12cbn6ejk.apps.googleusercontent.com',
    iosBundleId: 'com.example.mis',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6ho2oarreidNRTCFr9zHPwliMxOYMs74',
    appId: '1:960446114350:ios:35cd877ee8f37c61854dbf',
    messagingSenderId: '960446114350',
    projectId: 'malov-mis',
    storageBucket: 'malov-mis.appspot.com',
    iosClientId: '960446114350-c1sv1h1v376rg7g7lpft1rt12cbn6ejk.apps.googleusercontent.com',
    iosBundleId: 'com.example.mis',
  );
}
